### ISSUE TITLE
Doesn't support symbol keys

### ISSUE THREAD

**Issue by WoLfulus** [gvergnaud/ts-pattern#165] opened 2023-06-10 01:58 UTC
**Describe the bug**

ts-pattern ignores symbol keys.

```ts

    const meta = Symbol();

    const Post = {
      [meta]: {
        title: P.string,
      },
    };

    const post = {
      [meta]: {
        title: "Hello",
      },
    };

    const notPost = {
      hello: "world",
    };

    const getTitle = (value: any) =>
      match(value)
        .with(Post, (obj) => obj[meta].title)
        .otherwise(() => "No title");

    getTitle(post); //?  Hello
    getTitle(notPost); //?  TypeError: Cannot read properties...

```

**Versions**
- TypeScript version: ^5.0.4
- ts-pattern version: ^4.3.0
- environment: node 18.16.0

**Comment by gvergnaud** [comment] 2023-06-10 11:19
By default symbol keys aren't enumerable in JavaScript, so a function taking this object has no way to know that this key exists (It's one of the main point of symbols). That said, I think you can make your symbol key enumerable using `defineProperty` 

```ts
Object.defineProperty(Post, meta, {
    value: { title: P.string },
    enumerable: true
});
```

Hope that helps. Closing the issue since I believe this is expected behavior

**Closed by gvergnaud** 2023-06-10 11:19 UTC

**Comment by WoLfulus** [comment] 2023-06-10 12:24
I'll give it a try! Thanks!
