### ISSUE TITLE
Type '"error"' is not assignable to type 'KnownPattern<"ok">

### ISSUE THREAD

**Issue by JesterXL** [gvergnaud/ts-pattern#194] opened 2023-09-26 16:01 UTC
**Describe the bug**

I cannot compile the basic example in TypeScript 5.2.2 (maybe it's my VSCode, or Vite config?). In VSCode and running `npx tsc` I get:

```
Type '"error"' is not assignable to type 'KnownPattern<"ok"> | undefined'.ts(2322)
(property) type?: KnownPattern<"ok"> | undefined
```

**Code Sandbox with a minimal reproduction case**

It's just the standard code y'all provide:
```
type Data =
  | { type: 'text'; content: string }
  | { type: 'img'; src: string };

type Result =
  | { type: 'ok'; data: Data }
  | { type: 'error'; error: Error };

const result: Result = ...;

// The type: 'error' part is what it doesn't like
const html = match(result)
  .with({ type: 'error' }, () => `<p>Oups! An error occured</p>`)
  .with({ type: 'ok', data: { type: 'text' } }, (res) => `<p>${res.data.content}</p>`)
  .with({ type: 'ok', data: { type: 'img', src: P.select() } }, (src) => `<img src=${src} />`)
  .exhaustive();
```

**Versions**
- TypeScript version: 5.2.2
- ts-pattern version: 5.0.5
- environment: browser - Firefox + 117.0.1 / node version - 19.3.0

<img width="1048" alt="Screenshot 2023-09-26 at 12 00 31 PM" src="https://github.com/gvergnaud/ts-pattern/assets/424737/36c6ec75-5288-4129-bab0-e1a98ae145c1">

**Comment by gvergnaud** [comment] 2023-09-27 01:31
Closing because I don't reproduce this: [Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbziAhjAxgCwDRwApwC+cAZlBCHAOQwDOAtGGjAKZQB2VA3AFA8wBPMCzgARNCjgBeHnDgAfRHEHCAXNVYAPGNzjoI7VofW0YUYOwDmRWQqUqW6qqEu7aUdCbMXrhXvyERACUWWgBXABt4GTlFJAcnCABrXQATCXVxGElCWzjlQKc2cihdYuh1AFEoEqJ-VJZ0CJQoEX12UzhW8Kj1EJ6Yf3bOzBgQCOlkNCwACm7ImABKWwA6AHdgGEwZ+MLqctKiXBnF6QA+OAADAB4wM4B5MLBaAEI4AEF2OAO4CHR0MKtVLXAD0d0uyzk602212amoySouHS2XUcMcGhY2ioRCOcDmoVOUguNzuABIEN0ViiUCt2kYYIRQeDIXBoVsdgV4VREciMvY9s4QK5cO5PPgVrQWBFGjATrjCMcxUSSdcXHAxVIKWLiCCzhDVljMCgwqZgAA3FgnLhAA)

I suspect it's because you've replace the result declaration by a `{ type: 'ok', ... }` object literal, which will lead typescript to infer a narrower type for `result`: [Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbziAhjAxgCwDRwApwC+cAZlBCHAOQwDOAtGGjAKZQB2VA3AFA8wBPMCzgARNCjgBeHnDgAfRHEHCAXNVYAPGNzjoI7VofW0YUYOwDmRWQqUqW6qqEu7aUdCbMXrhXvyERACUWWgBXABt4GTlFJAcnCABrXQATCXVxGElCWzjlQKc2cihdYuh1AFEoEqJ-fXZTOChQyJh1EPCo6XtC6mSqXHTs9QQE6hdBuHdPahQqIjq+BqbMGBAIntQMTAAKFq6YAEpbADoAd2AYPfi+qnLSolxdo+kAPjgAAwAeMDeAeTCYFoAEI4ABBdhwB5wCDodBhFqpb4Aej+nxOcguVxuBTU-RSQwyvXxNBY2gWxEIzwOrykHx+fwAJAgDqdhihTg0jDBCKj0Zi4NjrrtbqSBkSRiTHBMQK5cDN1HhTrQWBEWOgYC9FtS4LsZnSGd8XNMPFIWTNiCi3hizuTMCgwqZgAA3FgvLhAA)

**Closed by gvergnaud** 2023-09-27 01:31 UTC

**Comment by JesterXL** [comment] 2023-09-29 15:58
I appreciate you taking the time to review this! I did exactly what you said in the 2nd Playground link. However, I don't understand your first. I'm coming from Elm/ReScript, and JavaScript's Folktale v2 so I usually create Result/Options "things" and then shove them to a match function.

I tried modifying that 2nd Playground you sent to:

```javascript
 const myData:Data = { type: 'text', content: 'test' }
 const myOk:Result = { type: 'ok', data: myData }
 const result: Result = myOk
```

But it gave me same error, lol. I feel like I'm missing something fundamental.

**Comment by JesterXL** [comment] 2023-09-29 15:59
Er, wait... I commented out the error and it worked. Is that because the compiler _knew_ I wasn't creating an error, or ... wat...

**Comment by JesterXL** [comment] 2023-09-29 16:01
Ah, yes, I just did the opposite and created an error, and the ok's started failing to compile. NOW I get it. So, what's the point of `exhaustive` if it's already exhaustive in the compile step?

**Comment by gvergnaud** [comment] 2023-09-29 18:13
If you're code is made of hardcoded object literals, then there's definitely no point in using pattern matching (or even if statements for that matter). The thing to understand here is that TypeScript is smart enough to know that the runtime value will always be `Ok` if you hardcode it, it will give it the type `Ok` instead of `Option` (in Elm/rescript lingo).

In a real world example, you would be in a context where you actually don't know what runtime value your function will receive, and neither does TypeScript. In this case, ts-pattern provides pattern-matching and exhaustiveness checking, similar to the builtin pattern matching syntax in elm/rescript.

**Comment by JesterXL** [comment] 2023-09-29 20:21
That helps, appreciate it!
