### ISSUE TITLE
Exhaustiveness check does not work

### ISSUE THREAD

**Issue by dermeister** [gvergnaud/ts-pattern#168] opened 2023-06-28 14:19 UTC
**Describe the bug**
Exhaustiveness check does not work when using enum elements of number type as discriminants.

**Code Sandbox with a minimal reproduction case**
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbziAhjAxgCzgXzgMyghDgHIYBnAWjDRgFMoA7UgbgCh30ImL56mAVxIBRISQTs4cAGLAofOABopcAMr1uTACbL2OTjACeYerPmKAvIjgBrYDoBccMcIB0chfAPHT6zTy61kj2Ti7ibhpauj4mZgAqcXDWnooAPv7RnFqK8MF2DtrOriAeFt5wKBRwiabsqBiYABQwAJSqbgDuwDDNIYXFEaneSnBNrckAfOHuw+3SXT19BWElkQE6uErjUzOlUYHzcG70AB6YKIJ8wABu9ONAA

**Versions**
- TypeScript version: 5.0.4
- ts-pattern version: 5.0.1
- environment: node v20.1.0

It seems that the problem is that conditional type like ```number extends Enum.Element ? false : true``` returns false which is used in IsLiteral check. If enum elements are of string type, then everything works correct. I guess that this problem could be overcome with similar check: ``` `${number}` extends `${Enum.Element}` ? false : true```

**Comment by gvergnaud** [comment] 2023-06-29 09:58
That's a know issue and a duplicate of #58 #162. It's annoying, but I prefer not to deviate from TypeScript's assignability behavior too much

**Closed by gvergnaud** 2023-06-29 09:58 UTC
