### ISSUE TITLE
Tuples within objects not selected properly

### ISSUE THREAD

**Issue by zbjornson** [gvergnaud/ts-pattern#67] opened 2021-12-24 03:43 UTC
**Describe the bug**
```ts
import {match, select} from "ts-pattern";

const r1 = match({$not: ["B"]})
	.with({$not: [select("term")]}, ({term}) => term)
	.run()
console.log(r1); // [ "B" ]

const r2 = match({a: [{$not: ["B"]}]})
	.with({a: [{$not: [select("term")]}]}, ({term}) => term)
	.run()
console.log(r2); // [ [ "B" ] ]
```

I was expecting these to both log `"B"`. Is this correct? Thanks!

**Code Sandbox with a minimal reproduction case**
https://codesandbox.io/s/bitter-moon-hwnzz

**Versions**
- TypeScript version: 4.5.4
- ts-pattern version: 3.3.4
- environment: Node.js v 14.18.1

**Comment by gvergnaud** [comment] 2021-12-24 11:49
That's expected, this is a duplicate of #62 and #46.

Here is the relevant doc section: https://github.com/gvergnaud/ts-pattern#lists-arrays

This will probably change in the next major version, see: https://github.com/gvergnaud/ts-pattern/issues/46#issuecomment-917597868

**Closed** 2021-12-24 11:49 UTC
