### ISSUE TITLE
Feature: return the value directly

### ISSUE THREAD

**Issue by gideaoms** [gvergnaud/ts-pattern#246] opened 2024-04-13 03:53 UTC
Hi, congratulations for the lib.

I would like to know if there is a possibility to return the value directly when I don't need to use it.

How it works today:
```ts
match(5)
  .when(1, () => "one")
  .when(2, () => "two")
  .otherwise(() => "three or greater")
```

How I would like it to work:
```ts
match(5)
  .when(1, "one")
  .when(2, "two")
  .otherwise("three or greater")
```

**Comment by darrylnoakes** [comment] 2024-04-15 14:41
Duplicate of #100.

**Comment by gideaoms** [comment] 2024-04-15 14:56
> Duplicate of #100.

Thanks for letting me know, I'll close it.

**Closed** 2024-04-15 14:56 UTC
Labels: enhancement
