### ISSUE TITLE
Exhaustive fails when matching an enum

### ISSUE THREAD

**Issue by jakelazaroff** [gvergnaud/ts-pattern#58] opened 2021-10-27 22:24 UTC
**Describe the bug**
`.exhaustive` returns a false negative type error when matching an enum.

**Code Sandbox with a minimal reproduction case**
https://codesandbox.io/s/focused-chatterjee-exp2m

**Versions**
- TypeScript version: 4.3.2
- ts-pattern version: 3.3.3

**Comment by K4rakara** [comment] 2022-10-23 02:46
This should probably be closed or something, since the TypeScript team decided that this is the correct behavior... :facepalm:

**Comment by gvergnaud** [comment] 2022-10-24 11:28
Closing this thread since this is expected behavior

**Closed by gvergnaud** 2022-10-24 11:28 UTC
Labels: workaround provided
