### ISSUE TITLE
Matching on union property doesn't narrow the property

### ISSUE THREAD

**Issue by LBBO** [gvergnaud/ts-pattern#265] opened 2024-06-18 12:16 UTC
**Describe the bug**
When I try matching over a type that has a union property, I get a different result than when I match over a union type with the same property:

```ts
// Doesn't work
type Obj = {
    type: "foo" | "bar"
}

// Works
// type Obj =
//     | {
//           type: "foo";
//       }
//     | {
//           type: "bar";
//       };

declare const obj: Obj;

match(obj)
    .with({ type: "foo" }, () => "adsf")
    .otherwise(({ type }) => type satisfies 'bar'); // type is not narrowed correctly with the first Obj type
```

I understand that this may be due to some limitation, but if that's the case, perhaps the docs could be adjusted to explain this limitation explicitly.

**TypeScript playground with a minimal reproduction case**

Example: [Playground](https://www.typescriptlang.org/play/?jsx=0&ts=5.4.5#code/JYWwDg9gTgLgBAbziAhjAxgCwDRwApwC+cAZlBCHAEQwDOAtGGjAKZQB2VA3AFA8D0-OABEILWuwDk8AO7QA1jxgBPMCzgB5AEYArOAF5EPOCbgq1ALmokIEKnAA+1LSihUehPoLgB1BbQEhc3VtPX1A0xMnBAjIuLNVFisqGzteb3jPDNNo2PjTYOSXN3ShTN4eABMWdAAbV3V0CHZaeAhdK1CK1AxMAAp2nQBKY1MAOhlgGH6kQutbe0JcPqGDAD5qFEraEioRyLGIabZJ2hY+vtnEolX9DeC4WjRgHeBxOEliySGuIA)

**Versions**
- TypeScript version: 5.4.5
- ts-pattern version: ^5.0.8
- environment: TS playground

**Comment by gvergnaud** [comment] 2024-06-18 23:08
That's expected. Duplicate of #145,  #182 [details here](https://github.com/gvergnaud/ts-pattern/issues/145#issuecomment-1426771926)

**Closed by gvergnaud** 2024-06-18 23:08 UTC

**Comment by LBBO** [comment] 2024-06-19 07:34
Sorry for the duplicate and thanks for the links!
