### ISSUE TITLE
Seeing a non-exhaustive error even after handling all possible usecases

### ISSUE THREAD

**Issue by SambhavAnand** [gvergnaud/ts-pattern#162] opened 2023-05-16 19:48 UTC
I have the following enum:
```
enum EndPoint {
  GET,
  POST,
  PUT
}
```
And the following function:
```
export function choosePrompt(endpoint: EndPoint): string {
  let prompt = match<EndPoint, string>(endpoint)
    .with(
      EndPoint.GET,
      () => getReturnType
    )
    .with(
      EndPoint.POST,
      () => postReturnType
    )
    .with(EndPoint.PUT, () => putReturnType)
    .with(P._, () => {
      throw new Error("Invalid usecase");
    })
    .exhaustive();
  return prompt
}
```
However, unless I add the P._ wildcard match, I'm getting a NonExhaustiveError<EndPoint> error.
Any ideas on what could be causing this issue?

**Comment by gvergnaud** [comment] 2023-05-17 21:41
Hey, I think this is a duplicate of https://github.com/gvergnaud/ts-pattern/issues/58. Closing the issue

**Closed by gvergnaud** 2023-05-17 21:41 UTC
